BOARD_SIZE = 4

REPLAY_MEM_SIZE = 10000 * (2 * BOARD_SIZE ** 2)
DATA_SIZE_PER_ITERATION = 256 * (2 * BOARD_SIZE ** 2)
BATCH_SIZE = 32

ITERATIONS = 256
EPISODES_PER_ITERATION = 256
NUM_EVAL_GAMES = 128

INIT_TEMP = 0.1
TEMP_DECAY = 3 / 4
MIN_TEMP = 1 / 64

MCT_SEARCHES = 0  # If set to 0, MCTPolicies become simply QVals

WORKERS = 8

LOAD_SAVED_MODELS = True
EPISODES_DIR = 'episodes/'
CHECKPOINT_PATH = f'checkpoints/checkpoint_{BOARD_SIZE}x{BOARD_SIZE}.pt'
TMP_PATH = 'checkpoints/tmp_{}x{}.pt'.format(BOARD_SIZE, BOARD_SIZE)

DEMO_TRAJECTORY_PATH = 'logs/a_trajectory.png'
