#!/bin/bash
#PBS -l nodes=4:ppn=12
#PBS -l walltime=12:00:00
#PBS -l naccesspolicy=singleuser
#PBS -N go_ai
#PBS -e bin/checkpoints/log.txt
#PBS -o bin/checkpoints/stats.txt
#PBS -q cs
module load openmpi/3.1.1-intel-18.0

cd $PBS_O_WORKDIR
echo -n >bin/checkpoints/stats.txt
echo -n >bin/checkpoints/log.txt

mpiexec -n 48 --bind-to core python3 train.py --boardsize=9 --model=val --mcts=8 --temp=0.02 --baseline=1 \
--episodes=192 --evaluations=192 --episodesdir=/home/ezhuang2/scratch/

