#!/bin/bash
#PBS -l nodes=4:ppn=16
#PBS -l walltime=12:00:00
#PBS -l naccesspolicy=singleuser
#PBS -N go_ai
#PBS -e bin/log.txt
#PBS -o bin/stats.txt
#PBS -q cs
module load mvapich2/2.0b-intel-14.0

cd $PBS_O_WORKDIR
echo -n >bin/stats.txt
echo -n >bin/log.txt
mpiexec -n 64 -binding cpu:cores python3 train.py --boardsize=9 --mcts=8 --temp=0.03125 --tempsteps=30 --episodes=128 \
--evaluations=128 --episodesdir=/home/ezhuang2/scratch/